### ISSUE TITLE
Adding it to nuxt-community

### ISSUE THREAD

**Issue by atinux** [JulienTant/nuxtjs-dotenv-module#1]
Hi @JulienTant 

Great job on this module, it does the job perfectly and simple to use :clap: 

What do you think of transfering it to https://github.com/nuxt-community

This way you will be able to publish this module on `@nuxtjs/dotenv`

PS: Please mention me so I can see your answer into my mailbox

**Comment by JulienTant** [comment]
Hi @Atinux 

I'm ok with this, but can you first take a look at the tests ? I'll be happy to have your feedback on them because I'm pretty sure there must be a better way to test this, but being new on NuxtJS (I discovered it last Friday), I cannot think of a better way.

Thanks!

**Comment by atinux** [comment]
Actually your tests are great, I would not have done better :)

**Comment by JulienTant** [comment]
@Atinux I moved the project !

See you ( pour une bière ou un Perrier :-) )

**Comment by atinux** [comment]
Top :)

Je t'ajoute sur NPM pour le publier sur `@nuxtjs/dotenv`

Avec plaisir pour la biere !
